name: my_test
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  math_expressions: ^2.4.0
  shared_preferences: ^2.2.2
  logger: ^2.0.2
  english_words: ^4.0.0
  provider: ^6.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true